### ISSUE TITLE
Problem on syntax highlight when combining :adl and :durative-actions)

### ISSUE THREAD

**Issue by corot** [Pold87/myPDDL#2]
Hi, 
I think there can be a problem when combining durative actions and ADL constructions (forall and exists), as the syntax highlight stops working. However, the domain is correct for the planner (sgplan). Using both separately there's no problem at all. I send you by e-mail and screen capture and the project files.

Congratulations for the tool! Is very useful. Thanks!

**Comment by zeid** [comment]
I have the same problem where the text stops being highlighted (I have attached a screenshot).
![screenshot from 2015-11-17 13 02 23](https://cloud.githubusercontent.com/assets/1042747/11220011/a822908c-8d2b-11e5-933e-444119fb01e7.png)

**Comment by Pold87** [comment]
Thanks for your error reports and sorry for the very late reply @corot. I've changed the syntax highlighting in commit c9f9d97. Could you please check if it works? You might have to to remove myPDDL and reinstall it or you can simply overwrite the file myPDDL/syntax/pddl.tmLanguage with the newest version from GitHub.

**Comment by zeid** [comment]
Wow, check this out :+1: 

Thanks

![screenshot from 2015-11-17 15 03 05](https://cloud.githubusercontent.com/assets/1042747/11223167/8e62b56c-8d3c-11e5-98b4-6b977fbe2182.png)

**Comment by Pold87** [comment]
Nice, thanks :)
I've just made another small update, the lines with no spaces between the operator and the bracket (like `=(`) should now be highlighted, too.

**Comment by corot** [comment]
:ok_hand:
works fine now!
Thanks!

**Comment by zeid** [comment]
Thanks for your effort :)
