### ISSUE TITLE
Support for Atom 

### ISSUE THREAD

**Issue by nsalerni** [Pold87/myPDDL#3]
Hello,

I was wondering if it would be possible to bring myPDDL support for syntax highlighting to Atom (https://atom.io). This would be a really great feature, something I think a lot of people in AI would appreciate.

Thanks,
Nick

**Comment by Pold87** [comment]
Yeah, cool idea! 
I've converted the syntax highlighting from Sublime Text to Atom. Have a look at https://github.com/Pold87/myPDDL-Atom
or simply:
`apm install mypddl`
