### ISSUE TITLE
How to generate the PDDL diagram

### ISSUE THREAD

**Issue by zeid** [Pold87/myPDDL#4]
Hello,

This is not really an issue but a question. When you generate a PDDL diagram from sublime text, where is the diagram stored? How do I know it was generated?

Thank you,

zeid

**Comment by Pold87** [comment]
Hi,

If you generate the diagram using myPDDL with Sublime Text, the diagram is stored in a folder diagrams/ that is located in the same directory as your .pddl file.
If you generate the diagram using the command line (`myPDDL diagram mydomainfile.pddl`), the diagram is stored in a folder diagrams/ relative to the path where you invoked the command. 
Please make sure that myPDDL is in your $PATH (see also https://github.com/Pold87/myPDDL#important).  
Normally, the diagram should be displayed immediately after generation. Have a look at line 48 of the myPDDL file and change the variable `viewer` to the program that should be called after generation of the image. 
If it's not working, could you please call myPDDL diagram from command line and post the output / error log?

**Comment by zeid** [comment]
Oh thank you, I did found all the diagrams in the diagram directory :)
However, all I can see in my diagrams are just nodes and not the vertices connecting the nodes (see attached picture). This happens when I create the diagram with my domain file. When i create the diagram for the problem, the picture is just empty. I don't think my problem file is wrong since I can generate a PDDL plan.
![png-diagram5](https://cloud.githubusercontent.com/assets/1042747/11253878/013f2352-8e0c-11e5-8573-c60cb549060c.png)

**Comment by zeid** [comment]
Ok, I'm dumb. it makes sense that I don't have the nodes connected to each other since none of my type is a subtype. Sorry for the trouble :)

Have a good day.

**Comment by Pold87** [comment]
No worries, glad that it worked out in the end!
Thanks, you too.
